Fourth etam
yurkorudi/Matrix_module pull request #6
Opened 2022-05-07 18:23 UTC by yurkorudi

...

2022-05-08 16:12 UTC, petropistun requested changes

2022-05-08 16:12 UTC, petropistun commented on lib/matrix.py
> +        if self.is_digital() == True and obg.is_digital() == True:
а як щодо стрічковиї матриць?

2022-05-08 16:12 UTC, petropistun commented on run_all_tests.py
> +# import tests.file_append_testing
Знову всі тести закоментовані

2022-05-08 16:12 UTC, petropistun commented on run_all_tests.py
> +# import tests.file_append_testing
а де виправленя тестів по додаванні, відніманні та інших операцій?

2022-05-08 21:05 UTC, yurkorudi commented on lib/matrix.py
> +        if self.is_digital() == True and obg.is_digital() == True:
Ой, щось забув. Виправлю

2022-05-25 21:04 UTC, yurkorudi commented on lib/matrix.py
> +        if self.is_digital() == True and obg.is_digital() == True:
Додано функцію для порівняння стрічкових матриць

2022-05-25 21:04 UTC, yurkorudi commented on run_all_tests.py
> +# import tests.file_append_testing
Всі тести розкоментовано

2022-05-25 21:04 UTC, yurkorudi commented on run_all_tests.py
> +# import tests.file_append_testing
Тести виправлені

2022-06-01 09:31 UTC, merged